const personas = [
    {
      id: 1,
      rut_usuario: "11222333-5",
      nombre: "Juan",
      apellido: "Pérez",
      alias: "JPérez",
      fecha_nacimiento: "1990-05-12",
      email: "Juan1@gmail.com",
      edad: 34,
      costo: 50000,
      tipo_perfil: "usuario",
      url_imagen: "https://i.scdn.co/image/ab676161000051744b92b5f8b229337e40073443",
      genero: "masculino",
      comentario:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam saepe, ipsum quidem libero, rem iusto sed ipsa facilis at aspernatur repudiandae consequatur. Voluptatem placeat alias at assumenda. Doloremque, quae ducimus!"
    },
    {
      id: 2,
      rut_usuario: "22333444-6",
      nombre: "María",
      apellido: "Gómez",
      alias: "MGómez",
      fecha_nacimiento: "1988-08-25",
      email: "María2@gmail.com",
      edad: 36,
      costo: 50000,
      tipo_perfil: "administrador",
      url_imagen: "https://images.pexels.com/photos/415829/pexels-photo-415829.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      genero: "femenino",
      comentario:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam saepe, ipsum quidem libero, rem iusto sed ipsa facilis at aspernatur repudiandae consequatur. Voluptatem placeat alias at assumenda. Doloremque, quae ducimus!"
    },
    {
      id: 3,
      rut_usuario: "33444555-7",
      nombre: "Carlos",
      apellido: "López",
      alias: "CLópez",
      fecha_nacimiento: "1995-02-10",
      email: "Carlos3@gmail.com",
      edad: 29,
      costo: 50000,
      tipo_perfil: "cliente",
      url_imagen: "https://images.pexels.com/photos/771742/pexels-photo-771742.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      genero: "masculino",
      comentario:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam saepe, ipsum quidem libero, rem iusto sed ipsa facilis at aspernatur repudiandae consequatur. Voluptatem placeat alias at assumenda. Doloremque, quae ducimus!"
    },
    {
      id: 4,
      rut_usuario: "44555666-8",
      nombre: "Ana",
      apellido: "Martínez",
      alias: "AMartínez",
      fecha_nacimiento: "1992-11-15",
      email: "Ana4@gmail.com",
      edad: 32,
      costo: 50000,
      tipo_perfil: "usuario",
      url_imagen: "https://images.pexels.com/photos/1040881/pexels-photo-1040881.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      genero: "femenino",
      comentario:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam saepe, ipsum quidem libero, rem iusto sed ipsa facilis at aspernatur repudiandae consequatur. Voluptatem placeat alias at assumenda. Doloremque, quae ducimus!"
    },
    {
      id: 5,
      rut_usuario: "55666777-9",
      nombre: "Pedro",
      apellido: "Rojas",
      alias: "PRojas",
      fecha_nacimiento: "1993-07-20",
      email: "Pedro5@gmail.com",
      edad: 31,
      costo: 50000,
      tipo_perfil: "administrador",
      url_imagen: "https://images.pexels.com/photos/14755204/pexels-photo-14755204.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      genero: "masculino",
      comentario:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam saepe, ipsum quidem libero, rem iusto sed ipsa facilis at aspernatur repudiandae consequatur. Voluptatem placeat alias at assumenda. Doloremque, quae ducimus!"
    },
    {
      id: 6,
      rut_usuario: "66777888-1",
      nombre: "Luisa",
      apellido: "Fernández",
      alias: "LFernández",
      fecha_nacimiento: "1991-03-28",
      email: "Luisa6@gmail.com",
      edad: 33,
      costo: 50000,
      tipo_perfil: "cliente",
      url_imagen: "https://images.pexels.com/photos/27081695/pexels-photo-27081695/free-photo-of-moda-gafas-de-sol-mujer-retrato.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      genero: "femenino",
      comentario:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam saepe, ipsum quidem libero, rem iusto sed ipsa facilis at aspernatur repudiandae consequatur. Voluptatem placeat alias at assumenda. Doloremque, quae ducimus!"
    },
    {
      id: 7,
      rut_usuario: "77888999-2",
      nombre: "Roberto",
      apellido: "García",
      alias: "RGarcía",
      fecha_nacimiento: "1985-12-05",
      email: "Roberto7@gmail.com",
      edad: 39,
      costo: 50000,
      tipo_perfil: "usuario",
      url_imagen: "https://images.pexels.com/photos/6571981/pexels-photo-6571981.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      genero: "masculino",
      comentario:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam saepe, ipsum quidem libero, rem iusto sed ipsa facilis at aspernatur repudiandae consequatur. Voluptatem placeat alias at assumenda. Doloremque, quae ducimus!"
    },
    {
      id: 8,
      rut_usuario: "88999000-3",
      nombre: "Mónica",
      apellido: "Vargas",
      alias: "MVargas",
      fecha_nacimiento: "1989-09-12",
      email: "Mónica8@gmail.com",
      edad: 35,
      costo: 50000,
      tipo_perfil: "cliente",
      url_imagen: "https://images.pexels.com/photos/8490990/pexels-photo-8490990.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      genero: "femenino",
      comentario:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam saepe, ipsum quidem libero, rem iusto sed ipsa facilis at aspernatur repudiandae consequatur. Voluptatem placeat alias at assumenda. Doloremque, quae ducimus!"
    },
    {
      id: 9,
      rut_usuario: "99000111-4",
      nombre: "Javier",
      apellido: "Cruz",
      alias: "JCruz",
      fecha_nacimiento: "1987-04-18",
      email: "Javier9@gmail.com",
      edad: 37,
      costo: 50000,
      tipo_perfil: "administrador",
      url_imagen: "https://images.pexels.com/photos/4016611/pexels-photo-4016611.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      genero: "masculino",
      comentario:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam saepe, ipsum quidem libero, rem iusto sed ipsa facilis at aspernatur repudiandae consequatur. Voluptatem placeat alias at assumenda. Doloremque, quae ducimus!"
    },
    {
      id: 10,
      rut_usuario: "10111222-5",
      nombre: "Camila",
      apellido: "Silva",
      alias: "CSilva",
      fecha_nacimiento: "1996-01-30",
      email: "Camila10@gmail.com",
      edad: 28,
      costo: 50000,
      tipo_perfil: "usuario",
      url_imagen: "https://images.pexels.com/photos/11805706/pexels-photo-11805706.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      genero: "femenino",
      comentario:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam saepe, ipsum quidem libero, rem iusto sed ipsa facilis at aspernatur repudiandae consequatur. Voluptatem placeat alias at assumenda. Doloremque, quae ducimus!"
    },
    // ... Continúa con los demás objetos ...
  ];
  
  export default personas;
  